import { makeAutoObservable } from 'mobx';

class library {
  // A1 - 376 words
  custom = [
    { en: ' Tired', ru: 'Усталый' },
    { en: ' Warm', ru: 'Теплый' },
    { en: ' Weak', ru: 'Слабый' },
    { en: ' Responsible', ru: 'Надежный' },
    { en: ' International', ru: 'Международный' },
    { en: ' Remote', ru: 'Удаленный' },
    { en: ' Recent', ru: 'Недавний' },
    { en: ' Necessary', ru: 'Необходимый' },
    { en: ' Independent', ru: 'Независимый' },
    { en: ' Confident', ru: 'Уверенный' },
    { en: 'Leisure time', ru: 'Досуг' },
    { en: 'Permission', ru: 'Разрешение' },
    { en: ' To bring', ru: 'Приносить' },
    { en: ' Behavior', ru: 'Поведение' },
    { en: ' Attitude', ru: 'Отношение' },
    { en: ' To leave', ru: 'Оставлять' },
    { en: ' To pray', ru: 'Молиться' },
    { en: ' To stay', ru: 'Оставаться' },
    { en: ' To let', ru: 'Позволять' },
    { en: ' To lead', ru: 'Вести' },
    { en: ' To discover', ru: 'Исследовать' },
    { en: ' To introduce', ru: 'Представить' },
    { en: ' To appear', ru: 'Появляться' },
    { en: ' To disappear', ru: 'Исчезать' },
    { en: ' To decide', ru: 'Решать' },
    { en: ' To propose', ru: 'Предлагать' },
    { en: ' To hesitate', ru: 'Сомневаться' },
    { en: ' wind', ru: 'Ветер' },
    { en: ' south', ru: 'Юг' },
    { en: ' west', ru: 'Запад' },
    { en: ' east', ru: 'Восток' },
    { en: ' north', ru: 'Север' },
    { en: ' evening', ru: 'Вечер' },
    { en: ' insect', ru: 'Насекомое' },
    { en: ' Relatives', ru: 'Родственники' },
    { en: ' nephew', ru: 'Племянник' },
    { en: ' child', ru: 'Ребенок' },
    { en: ' children', ru: 'Дети' },
    { en: ' joy', ru: 'Радость' },
  ];
  A1verbs = [
    { en: ' To be', ru: 'Быть' },
    { en: ' To do', ru: 'Делать' },
    { en: ' To feel', ru: 'Чувствовать' },
    { en: ' To see', ru: 'Видеть' },
    { en: ' To hear', ru: 'Слышать' },
    { en: ' To run', ru: 'Бежать' },
    { en: ' To get', ru: 'Получать' },
    { en: ' To make', ru: 'Сделать' },
    { en: ' To cook', ru: 'Готовить' },
    { en: ' To sing', ru: 'Петь' },
    { en: ' To speak', ru: 'Разговаривать' },
    { en: ' To say', ru: 'Говорить' },
    { en: ' To tell', ru: 'Рассказывать' },
    { en: ' To take', ru: 'Брать' },
    { en: ' To sit', ru: 'Садиться' },
    { en: ' To stand', ru: 'Стоять' },
    { en: ' To laugh', ru: 'Смеяться' },
    { en: ' To smile', ru: 'Улыбаться' },
    { en: ' To open', ru: 'Открывать' },
    { en: ' To close', ru: 'Закрывать' },
    { en: ' To love', ru: 'Любить' },
    { en: ' To like', ru: 'Нравиться' },
    { en: ' To give', ru: 'Давать' },
    { en: ' To bring', ru: 'Приносить' },
    { en: ' To breath', ru: 'Дышать' },
    { en: ' To buy', ru: 'Покупать' },
    { en: ' To sell', ru: 'Продавать' },
    { en: ' To forget', ru: 'Забывать' },
    { en: ' To believe', ru: 'Верить' },
    { en: ' To have', ru: 'Иметь' },
    { en: ' To go', ru: 'Идти' },
    { en: ' To know', ru: 'Знать' },
    { en: ' To think', ru: 'Думать' },
    { en: ' To come', ru: 'Приходить' },
    { en: ' To want', ru: 'Хотеть' },
    { en: ' To use', ru: 'Использовать' },
    { en: ' To find', ru: 'Находить' },
    { en: ' To work', ru: 'Работать' },
    { en: ' To eat', ru: 'Есть' },
    { en: ' To drink', ru: 'Пить' },
    { en: ' To write', ru: 'Писать' },
    { en: ' To read', ru: 'Читать' },
    { en: ' To call', ru: 'Звонить' },
    { en: ' To try', ru: 'Пытаться' },
    { en: ' To need', ru: 'Нуждаться' },
    { en: ' To become', ru: 'Становиться' },
    { en: ' To put', ru: 'Класть' },
    { en: ' To leave', ru: 'Оставлять' },
    { en: ' To pay', ru: 'Платить' },
    { en: ' To play', ru: 'Играть' },
    { en: ' To pray', ru: 'Молиться' },
    { en: ' To stay', ru: 'Оставаться' },
    { en: ' To mean', ru: 'Означать' },
    { en: ' To keep', ru: 'Хранить' },
    { en: ' To let', ru: 'Позволять' },
    { en: ' To begin', ru: 'Начинать' },
    { en: ' To start', ru: 'Стартовать' },
    { en: ' To finish', ru: 'Заканчивать' },
    { en: ' To help', ru: 'Помогать' },
    { en: ' To show', ru: 'Показывать' },
    { en: ' To cry', ru: 'Плакать' },
    { en: ' To move', ru: 'Двигаться' },
    { en: ' To jump', ru: 'Прыгать' },
    { en: ' To live', ru: 'Жить' },
    { en: ' To die', ru: 'Умирать' },
    { en: ' To happen', ru: 'Случаться' },
    { en: ' To lose', ru: 'Проигрывать' },
    { en: ' To hate', ru: 'Ненавидеть' },
    { en: ' To include', ru: 'Включать' },
    { en: ' To turn on', ru: 'Включать' },
    { en: ' To turn off', ru: 'Выключать' },
    { en: ' To continue', ru: 'Продолжать' },
    { en: ' To change', ru: 'Менять' },
    { en: ' To wash', ru: 'Мыть' },
    { en: ' To clean', ru: 'Очищать' },
    { en: ' To lead', ru: 'Вести' },
    { en: ' To understand', ru: 'Понимать' },
    { en: ' To watch', ru: 'Смотреть' },
    { en: ' To discover', ru: 'Исследовать' },
    { en: ' To imagine', ru: 'Представлять' },
    { en: ' To introduce', ru: 'Представить' },
    { en: ' To follow', ru: 'Следовать' },
    { en: ' To create', ru: 'Создавать' },
    { en: ' To grow', ru: 'Расти' },
    { en: ' To spend', ru: 'Тратить' },
    { en: ' To win', ru: 'Выигрывать' },
    { en: ' To offer', ru: 'Предлагать' },
    { en: ' To learn', ru: 'Изучать' },
    { en: ' To appear', ru: 'Появляться' },
    { en: ' To disappear', ru: 'Исчезать' },
    { en: ' To build', ru: 'Строить' },
    { en: ' To break', ru: 'Ломать' },
    { en: ' To send', ru: 'Посылать' },
    { en: ' To fall', ru: 'Падать' },
    { en: ' To cut', ru: 'Резать' },
    { en: ' To achieve', ru: 'Достигать' },
    { en: ' To communicate', ru: 'Общаться' },
    { en: ' To kill', ru: 'Убивать' },
    { en: ' To pass', ru: 'Проходить' },
    { en: ' To fly', ru: 'Летать' },
    { en: ' To swim', ru: 'Плавать' },
    { en: ' To decide', ru: 'Решать' },
    { en: ' To return', ru: 'Возвращаться' },
    { en: ' To hope', ru: 'Надеяться' },
    { en: ' To explain', ru: 'Объяснять' },
    { en: ' To propose', ru: 'Предлагать' },
    { en: ' To develop', ru: 'Развивать' },
    { en: ' To support', ru: 'Поддерживать' },
    { en: ' To dance', ru: 'Танцевать' },
    { en: ' To draw', ru: 'Рисовать' },
    { en: ' To book', ru: 'Бронировать' },
    { en: ' To be afraid', ru: 'Бояться' },
    { en: ' To agree', ru: 'Соглашаться' },
    { en: ' To check up', ru: 'Проверять' },
    { en: ' To delete', ru: 'Удалять' },
    { en: ' To choose', ru: 'Выбирать' },
    { en: ' To catch', ru: 'Ловить' },
    { en: ' To ask', ru: 'Спрашивать' },
    { en: ' To answer', ru: 'Отвечать' },
    { en: ' To hesitate', ru: 'Сомневаться' },
  ];
  A1nouns = [
    { en: ' air', ru: 'Воздух' },
    { en: ' wind', ru: 'Ветер' },
    { en: ' water', ru: 'Вода' },
    { en: ' west', ru: 'Запад' },
    { en: ' east', ru: 'Восток' },
    { en: ' north', ru: 'Север' },
    { en: ' south', ru: 'Юг' },
    { en: ' tree', ru: 'Дерево' },
    { en: ' sea', ru: 'Море' },
    { en: ' ocean', ru: 'Океан' },
    { en: ' rock', ru: 'Скала' },
    { en: ' plant', ru: 'Растение' },
    { en: ' flower', ru: 'Цветок' },
    { en: ' forest', ru: 'Лес' },
    { en: ' person', ru: 'Личность' },
    { en: ' night', ru: 'Ночь' },
    { en: ' morning', ru: 'Утро' },
    { en: ' day', ru: 'День' },
    { en: ' evening', ru: 'Вечер' },
    { en: ' life', ru: 'Жизнь' },
    { en: ' mountain', ru: 'Гора' },
    { en: ' land', ru: 'Земля' },
    { en: ' house', ru: 'Дом' },
    { en: ' fire', ru: 'Огонь' },
    { en: ' country', ru: 'Страна' },
    { en: ' animal', ru: 'Животное' },
    { en: ' bird', ru: 'Птица' },
    { en: ' fish', ru: 'Рыба' },
    { en: ' insect', ru: 'Насекомое' },
    { en: ' city', ru: 'Город' },
    { en: ' world', ru: 'Мир' },
    { en: ' boy', ru: 'Мальчик' },
    { en: ' girl', ru: 'Девочка' },
    { en: ' mother', ru: 'Мама' },
    { en: ' father', ru: 'Отец' },
    { en: ' son', ru: 'Сын' },
    { en: ' daughter', ru: 'Дочь' },
    { en: ' baby', ru: 'Малыш' },
    { en: ' family', ru: 'Семья' },
    { en: ' grand mother', ru: 'Бабушка' },
    { en: ' grand father', ru: 'Дедушка' },
    { en: ' children', ru: 'Дети' },
    { en: ' home', ru: 'Дом' },
    { en: ' love', ru: 'Любовь' },
    { en: ' apartment', ru: 'Квартира' },
    { en: ' joy', ru: 'Радость' },
    { en: ' nephew', ru: 'Племянник' },
    { en: ' aunt', ru: 'Тетя' },
    { en: ' uncle', ru: 'Дядя' },
    { en: ' cousin', ru: 'Двоюродная Сестра' },
    { en: ' man', ru: 'Мужчина' },
    { en: ' woman', ru: 'Женщина' },
    { en: ' child', ru: 'Ребенок' },
    { en: ' sister', ru: 'Сестра' },
    { en: ' brother', ru: 'Брат' },
    { en: ' Relatives', ru: 'Родственники' },
    { en: ' friend', ru: 'Друг' },
    { en: ' wife', ru: 'Жена' },
    { en: ' husband', ru: 'Муж' },
    { en: ' address', ru: 'Адрес' },
    { en: ' happiness', ru: 'Счастье' },
    { en: ' People', ru: 'Люди' },
    { en: ' phone', ru: 'Телефон' },
    { en: ' question', ru: 'Вопрос' },
    { en: ' place', ru: 'Место' },
    { en: ' market', ru: 'Рынок' },
    { en: ' order', ru: 'Заказ' },
    { en: ' food', ru: 'Еда' },
    { en: ' work', ru: 'Работа' },
    { en: ' communication', ru: 'Общение' },
    { en: ' story', ru: 'История' },
    { en: ' relax', ru: 'Отдых' },
    { en: ' time', ru: 'Время' },
    { en: ' word', ru: 'Слово' },
    { en: ' dialogue', ru: 'Диалог' },
    { en: ' meeting', ru: 'Встреча' },
    { en: ' week', ru: 'Неделя' },
    { en: ' distance', ru: 'Дистанция' },
    { en: ' club', ru: 'Клуб' },
    { en: ' theatre', ru: 'Театр' },
    { en: ' cinema', ru: 'Кинотеатр' },
    { en: ' coffee shop', ru: 'Кофейня' },
    { en: ' friendship', ru: 'Дружба' },
    { en: ' behavior', ru: 'Поведение' },
    { en: ' attitude', ru: 'Отношение' },
    { en: ' student', ru: 'Студент' },
    { en: ' university', ru: 'Университет' },
    { en: ' union', ru: 'Объединение' },
    { en: ' party', ru: 'Вечеринка' },
    { en: ' date', ru: 'Свидание' },
    { en: ' sweetheart', ru: 'Партнер' },
    { en: ' leisure time', ru: 'Досуг' },
    { en: ' road', ru: 'Дорога' },
    { en: ' ticket', ru: 'Билет' },
    { en: ' map', ru: 'Карта' },
    { en: ' motel', ru: 'Мотель' },
    { en: ' highway', ru: 'Шоссе' },
    { en: ' reception', ru: 'Регистратура' },
    { en: ' wallet', ru: 'Бумажник' },
    { en: ' bank', ru: 'Банк' },
    { en: ' subway', ru: 'Метро' },
    { en: ' cab', ru: 'Такси' },
    { en: ' parking', ru: 'Парковка' },
    { en: ' food order', ru: 'Заказ еды' },
    { en: ' cash', ru: 'Наличные' },
    { en: ' passport', ru: 'Паспорт' },
    { en: ' permission', ru: 'Разрешение' },
    { en: ' lawyer', ru: 'Адвокат' },
    { en: ' problem', ru: 'Проблема' },
    { en: ' waiting room', ru: 'Зал ожидания' },
    { en: ' transfer', ru: 'Пересадка' },
    { en: ' bag', ru: 'Сумка' },
    { en: ' suitcase', ru: 'Чемодан' },
    { en: ' property', ru: 'Имущество' },
    { en: ' law', ru: 'Закон' },
    { en: ' police station', ru: 'Полицейский участок' },
    { en: ' price', ru: 'Цена' },
    { en: ' price list', ru: 'Ценник' },
    { en: ' courier', ru: 'Курьер' },
    { en: ' delivery', ru: 'Доставка' },
    { en: ' location', ru: 'Местоположение' },
    { en: ' route', ru: 'Маршрут' },
    { en: ' agreement', ru: 'Договор' },
    { en: ' hospital', ru: 'Больница' },
    { en: ' ambulance', ru: 'Скорая помощь' },
  ];
  A1adjectives = [
    { en: ' Afraid', ru: 'Напуганный' },
    { en: ' Angry', ru: 'Сердитый' },
    { en: ' Asleep', ru: 'Спящий' },
    { en: ' Attentive', ru: 'Внимательный' },
    { en: ' Available', ru: 'Доступный' },
    { en: ' Basic', ru: 'Базовый' },
    { en: ' Beautiful', ru: 'Красивый' },
    { en: ' Big', ru: 'Большой' },
    { en: ' Brave', ru: 'Смелый' },
    { en: ' Busy', ru: 'Занятой' },
    { en: ' Calm', ru: 'Спокойный' },
    { en: ' Careful', ru: 'Внимательный' },
    { en: ' Cheap', ru: 'Дешевый' },
    { en: ' Clean', ru: 'Чистый' },
    { en: ' Clever', ru: 'Умный' },
    { en: ' Cold', ru: 'Холодный' },
    { en: ' Comfortable', ru: 'Комфортный' },
    { en: ' Confident', ru: 'Уверенный' },
    { en: ' Constant', ru: 'Постоянный' },
    { en: ' Curious', ru: 'Любопытный' },
    { en: ' Dangerous', ru: 'Опасный' },
    { en: ' Dark', ru: 'Темный' },
    { en: ' Deep', ru: 'Глубокий' },
    { en: ' Different', ru: 'Разный' },
    { en: ' Difficult', ru: 'Трудный' },
    { en: ' Dirty', ru: 'Грязный' },
    { en: ' Easy', ru: 'Легкий' },
    { en: ' Every', ru: 'Каждый' },
    { en: ' Expensive', ru: 'Дорогой' },
    { en: ' Exact', ru: 'Точный' },
    { en: ' Fast', ru: 'Быстрый' },
    { en: ' Fair', ru: 'Светлый' },
    { en: ' Fine', ru: 'Замечательный' },
    { en: ' Foreign', ru: 'Иностранный' },
    { en: ' Free', ru: 'Свободный' },
    { en: ' Fresh', ru: 'Свежий' },
    { en: ' Full', ru: 'Полный' },
    { en: ' Funny', ru: 'Забавный' },
    { en: ' Guilty', ru: 'Виновный' },
    { en: ' Healthy', ru: 'Здоровый' },
    { en: ' Hard', ru: 'Тяжелый' },
    { en: ' Helpful', ru: 'Полезный' },
    { en: ' Honest', ru: 'Честный' },
    { en: ' Hot', ru: 'Горячий' },
    { en: ' Hungry', ru: 'Голодный' },
    { en: ' Important', ru: 'Важный' },
    { en: ' Illegal', ru: 'Нелегальный' },
    { en: ' Impossible', ru: 'Невозможный' },
    { en: ' Independent', ru: 'Независимый' },
    { en: ' Interesting', ru: 'Интересный' },
    { en: ' Kind', ru: 'Добрый' },
    { en: ' Legal', ru: 'Законный' },
    { en: ' Little', ru: 'Маленький' },
    { en: ' Lucky', ru: 'Удачливый' },
    { en: ' Necessary', ru: 'Необходимый' },
    { en: ' Normal', ru: 'Нормальный' },
    { en: ' Old', ru: 'Старый' },
    { en: ' Opposite', ru: 'Противоположный' },
    { en: ' Perfect', ru: 'Идеальный' },
    { en: ' Poor', ru: 'Бедный' },
    { en: ' Powerful', ru: 'Мощный' },
    { en: ' Possible', ru: 'Возможный' },
    { en: ' Quiet', ru: 'Тихий' },
    { en: ' Rare', ru: 'Редкий' },
    { en: ' Recent', ru: 'Недавний' },
    { en: ' Relevant', ru: 'Релевантный' },
    { en: ' Remote', ru: 'Удаленный' },
    { en: ' Safe', ru: 'Безопасный' },
    { en: ' Short', ru: 'Короткий' },
    { en: ' Small', ru: 'Маленький' },
    { en: ' Strange', ru: 'Незнакомый' },
    { en: ' Successful', ru: 'Успешный' },
    { en: ' Tasty', ru: 'Вкусный' },
    { en: ' Terrible', ru: 'Жуткий' },
    { en: ' Tired', ru: 'Усталый' },
    { en: ' Warm', ru: 'Теплый' },
    { en: ' Weak', ru: 'Слабый' },
    { en: ' Responsible', ru: 'Надежный' },
    { en: ' Sad', ru: 'Грустный' },
    { en: ' International', ru: 'Международный' },
  ];
  A1adverbs = [
    { en: ' Together', ru: 'Вместе' },
    { en: ' According', ru: 'В соответствии' },
    { en: ' Again', ru: 'Снова' },
    { en: ' Always', ru: 'Всегда' },
    { en: ' Beautifully', ru: 'Красиво' },
    { en: ' Carefully', ru: 'Осторожно' },
    { en: ' Correctly', ru: 'Верно' },
    { en: ' Especially', ru: 'Особенно' },
    { en: ' Friendly', ru: 'Дружелюбно' },
    { en: ' Indeed', ru: 'Действительно' },
    { en: ' Above', ru: 'Выше' },
    { en: ' Accidentally', ru: 'Случайно' },
    { en: ' Actually', ru: 'На самом деле' },
    { en: ' Badly', ru: 'Плохо' },
    { en: ' Besides', ru: 'Помимо этого' },
    { en: ' Briefly', ru: 'Кратко' },
    { en: ' Certainly', ru: 'Конечно' },
    { en: ' Daily', ru: 'Ежедневно' },
    { en: ' Dreamily', ru: 'Мечтательно' },
    { en: ' Even', ru: 'Даже' },
    { en: ' Eventually', ru: 'В конце концов' },
    { en: ' Foolishly', ru: 'Глупо' },
    { en: ' Forward', ru: 'Вперед' },
    { en: ' Ever', ru: 'Когда-либо' },
    { en: ' Equally', ru: 'Одинаково' },
    { en: ' Fortunately', ru: 'К счастью' },
    { en: ' Honestly', ru: 'Честно' },
    { en: ' Instead', ru: 'Вместо' },
    { en: ' Inside', ru: 'Внутри' },
    { en: ' Also', ru: 'Также' },
    { en: ' Hardly', ru: 'С трудом' },
    { en: ' Lately', ru: 'Недавно' },
    { en: ' Less', ru: 'Меньше' },
    { en: ' Loudly', ru: 'Громко' },
    { en: ' Nearly', ru: 'Около' },
    { en: ' Never', ru: 'Никогда' },
    { en: ' Only', ru: 'Только' },
    { en: ' Once', ru: 'Один раз' },
    { en: ' Often', ru: 'Часто' },
    { en: ' Perhaps', ru: 'Возможно' },
    { en: ' Quickly', ru: 'Быстро' },
    { en: ' Probably', ru: 'Вероятно' },
    { en: ' Rarely', ru: 'Редко' },
    { en: ' Really', ru: 'Действительно' },
    { en: ' Sometimes', ru: 'Иногда' },
    { en: ' Yesterday', ru: 'Вчера' },
    { en: ' Thus', ru: 'Таким образом' },
    { en: ' Somehow', ru: 'Как-то' },
    { en: ' Soon', ru: 'Скоро' },
    { en: ' Regularly', ru: 'Регулярно' },
    { en: ' Somewhere', ru: 'Где-то' },
  ];
  constructor() {
    makeAutoObservable(this);
  }
}

export default new library();
